# Definition of various tests
test_1:
  testblock_1:
    publish_rate:
      - topic: /topic1
        groundtruth: 11
        groundtruth_epsilon: 1
      - topic: "topic2"
        groundtruth: 22
        groundtruth_epsilon: 1
  testblock_2:
    publish_rate:
      - topic: /topic3
        groundtruth: 33
        groundtruth_epsilon: 1
test_2:
  testblock_1:
    publish_rate:
      - topic: /topic1
      - topic: "topic2"
  testblock_3:
    publish_rate:
      - topic: /topic3