# Definition of various tests
test_1:
  testblock_1:
    time:
      - groundtruth: 3
        groundtruth_epsilon: 0.5
  testblock_2:
    time:
      - groundtruth: 5
        groundtruth_epsilon: 0.5
test_2:
  testblock_1:
    time:
  testblock_3:
    time:
