testblock_1:
  interface:
    - node: publisher1
      publishers: 
        - [topic1, std_msgs/String]
    - node: subscriber1
      subscribers: 
        - [topic2, std_msgs/Int32]

testblock_2:
  interface:
    - node: publisher1
      publishers: 
        - [topic1, std_msgs/String]
    - node: subscriber1
      subscribers: 
        - [topic2, std_msgs/Int32]
