# Definition of various tests
test_1:
  testblock_1:
    interface:
      - node: publisher1
        publishers: 
          - [topic1, std_msgs/String]
      - node: subscriber1
        subscribers: 
          - [topic2, std_msgs/Int32]
  testblock_2:
    interface:
      - node: publisher1
        publishers: 
          - [topic1, std_msgs/String]
      - node: subscriber1
        subscribers: 
          - [topic2, std_msgs/Int32]

test_2:
  testblock_1:
    interface:
      - node: publisher1
      - node: subscriber1
  testblock_2:
      - node: publisher1
      - node: subscriber1
# TODO: pub-sub, service server, service client?, action server, actionclient?
