testblock_circle:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
testblock_quadrat:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
testblock_all:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
    - topic: /tf
      root_frame: world
      measured_frame: reference4
