testblock_circle:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
      groundtruth: 6.28
      groundtruth_epsilon: 1.5
testblock_quadrat:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
      groundtruth: 8.0
      groundtruth_epsilon: 1.5
testblock_all:
  path_length:
    - topic: /tf
      root_frame: world
      measured_frame: reference1
      groundtruth: 14.28
      groundtruth_epsilon: 1.5
    - topic: /tf
      root_frame: world
      measured_frame: reference4
