testblock_circle:
  path_length:
    - topics: [/tf]
      root_frame: world
      measured_frame: reference1
      groundtruth: 6.28
      groundtruth_epsilon: 1.5
    - topics: [/tf, /tf_static]
      root_frame: world
      measured_frame: reference1_static
      groundtruth: 6.28
      groundtruth_epsilon: 1.5
testblock_quadrat:
  path_length:
    - topics: [/tf]
      root_frame: world
      measured_frame: reference1
      groundtruth: 8.0
      groundtruth_epsilon: 1.5
testblock_all:
  path_length:
    - topics: [/tf]
      root_frame: world
      measured_frame: reference1
      groundtruth: 14.28
      groundtruth_epsilon: 1.5
    - topics: [/tf]
      root_frame: world
      measured_frame: reference4
