test_suite_file: "config/test_suite.yaml"           # Path of the test_suite file
test_config_file: "config/test_config.yaml"         # Path of the test_config file
robot_config_path: "config/"                        # Folder which contains the robot_config files
test_repetitions: 1                                                  # Number of repetitions per test

test_application_path: "test/application.test"          # Path of the application test file
additional_launch_file: "launch/application.launch"     # Path of the additional launch file

bagfile_output: "/tmp/atf_test_app_path_length/data/"                                 # Folder for bagfile output
result_json_output: "/tmp/atf_test_app_path_length/results_json/"                            # Folder for the json files output
result_yaml_output: "/tmp/atf_test_app_path_length/results_yaml/"                           # Folder for the yaml files output

upload_data: false
upload_result: true

time_limit_recording: 30.0                                          # Time limit in seconds for recording (travis-ci has a maximum of 600s after which it will end the building process)
time_limit_analysing: 30.0                                          # Time limit in seconds for analysing (travis-ci has a maximum of 600s after which it will end the building process)
time_limit_uploading: 60.0                                          # Time limit in seconds for uploading (travis-ci has a maximum of 600s after which it will end the building process)
