# Definition of various tests
test_1:
  testblock_circle:
    path_length: 
      - [world, reference1]
  testblock_quadrat:
    path_length: 
      - [world, reference1]
  testblock_all:
    path_length: 
      - [world, reference1]
      - [reference1, reference2]
      - [reference1, reference3]
      - [reference1, reference4]
test_2:
  testblock_circle:
    path_length: 
      - [world, reference1]
  testblock_all:
    path_length:
      - [world, reference1]
