test_1:
  testblock_circle:
    path_length:
      - root_frame: world
        measured_frame: reference1
        groundtruth: 6.28
        groundtruth_epsilon: 0.5
  testblock_quadrat:
    path_length:
      - root_frame: world
        measured_frame: reference1
        groundtruth: 8.0
        groundtruth_epsilon: 0.5
  testblock_all:
    path_length:
      - root_frame: world
        measured_frame: reference1
        groundtruth: 14.28
        groundtruth_epsilon: 0.5
      - root_frame: world
        measured_frame: reference4
test_2:
  testblock_circle:
    path_length:
      - root_frame: world
        measured_frame: reference1
  testblock_quadrat:
    path_length:
      - root_frame: world
        measured_frame: reference1
  testblock_all:
    path_length:
      - root_frame: world
        measured_frame: reference1
      - root_frame: world
        measured_frame: reference4
